CREATE TABLE book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    author TEXT,
    cover_path TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE book_version (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL REFERENCES book (id) ON DELETE CASCADE,
    source_file_path TEXT NOT NULL,
    source_file_sha256 CHAR(64) NOT NULL,
    parser_version VARCHAR(64) NOT NULL,
    segmentation_rule_version VARCHAR(64) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (book_id, source_file_sha256)
);

CREATE TABLE chapter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_version_id BIGINT NOT NULL REFERENCES book_version (id) ON DELETE CASCADE,
    chapter_number INTEGER NOT NULL CHECK (chapter_number > 0),
    title TEXT NOT NULL,
    text_path TEXT NOT NULL,
    text_sha256 CHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    final_audio_path TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (book_version_id, chapter_number)
);

CREATE TABLE voice_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE,
    reference_audio_path TEXT,
    reference_audio_sha256 CHAR(64),
    reference_text TEXT,
    voice_design_description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE tts_preset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    engine VARCHAR(64) NOT NULL,
    model VARCHAR(128) NOT NULL,
    model_version VARCHAR(64) NOT NULL,
    style_instruction TEXT,
    speed NUMERIC(6, 3) NOT NULL DEFAULT 1.000,
    model_parameters JSONB NOT NULL DEFAULT '{}'::jsonb,
    segment_length INTEGER NOT NULL DEFAULT 1000 CHECK (segment_length > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE generation_job (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chapter_id BIGINT NOT NULL REFERENCES chapter (id) ON DELETE CASCADE,
    segment_index INTEGER NOT NULL CHECK (segment_index >= 0),
    segment_text TEXT NOT NULL,
    text_sha256 CHAR(64) NOT NULL,
    preset_snapshot JSONB NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    lease_owner VARCHAR(128),
    lease_expires_at TIMESTAMPTZ,
    error_code VARCHAR(128),
    error_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (chapter_id, segment_index)
);

CREATE TABLE audio_asset (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id BIGINT NOT NULL REFERENCES generation_job (id) ON DELETE CASCADE,
    file_path TEXT NOT NULL,
    format VARCHAR(16) NOT NULL,
    duration_ms BIGINT,
    sample_rate INTEGER,
    channels SMALLINT,
    size_bytes BIGINT,
    sha256 CHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (job_id, file_path)
);

CREATE TABLE worker_registration (
    worker_id VARCHAR(128) PRIMARY KEY,
    name VARCHAR(128) NOT NULL,
    capabilities JSONB NOT NULL DEFAULT '{}'::jsonb,
    token_hash TEXT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    last_heartbeat_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_book_status ON book (status);
CREATE INDEX idx_book_version_book_id ON book_version (book_id);
CREATE INDEX idx_chapter_status ON chapter (status);
CREATE INDEX idx_generation_job_status_lease ON generation_job (status, lease_expires_at);
CREATE INDEX idx_generation_job_chapter_id ON generation_job (chapter_id);
CREATE INDEX idx_audio_asset_job_id ON audio_asset (job_id);
CREATE INDEX idx_worker_registration_status ON worker_registration (status);
